from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f2a3b4c5d6e"
down_revision = "c3a1f4d2e9aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "CUSTOMER_ADMIN",
                "CUSTOMER_MERCHANT",
                name="chatconversationtype",
            ),
            nullable=False,
        ),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=True),
        sa.Column("admin_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column("customer_last_read_at", sa.DateTime(), nullable=True),
        sa.Column("merchant_last_read_at", sa.DateTime(), nullable=True),
        sa.Column("admin_last_read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_conversations_admin_id"),
            ["admin_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_chat_conversations_customer_id"),
            ["customer_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_chat_conversations_merchant_id"),
            ["merchant_id"],
            unique=False,
        )

    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=True),
        sa.Column("sender_role", sa.String(length=20), nullable=False),
        sa.Column(
            "msg_type",
            sa.Enum(
                "TEXT",
                "IMAGE",
                "PRODUCT_LINK",
                "EMOJI",
                name="chatmessagetype",
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("image_path", sa.String(length=255), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["chat_conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_messages_conversation_id"),
            ["conversation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_chat_messages_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_chat_messages_sender_id"),
            ["sender_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_messages_sender_id"))
        batch_op.drop_index(batch_op.f("ix_chat_messages_created_at"))
        batch_op.drop_index(batch_op.f("ix_chat_messages_conversation_id"))

    op.drop_table("chat_messages")
    with op.batch_alter_table("chat_conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_conversations_merchant_id"))
        batch_op.drop_index(batch_op.f("ix_chat_conversations_customer_id"))
        batch_op.drop_index(batch_op.f("ix_chat_conversations_admin_id"))

    op.drop_table("chat_conversations")
    # ### end Alembic commands ###
