from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c78dcd73667"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_slug"), ["slug"], unique=True
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("CUSTOMER", "MERCHANT", "ADMIN", name="userrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_email"), ["email"], unique=True
        )

    op.create_table(
        "addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recipient_name", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("province", sa.String(length=50), nullable=False),
        sa.Column("city", sa.String(length=50), nullable=False),
        sa.Column("district", sa.String(length=50), nullable=False),
        sa.Column("detail_address", sa.Text(), nullable=False),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("lat", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("lng", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("addresses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_addresses_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("actor_role", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_logs_created_at"),
            ["created_at"],
            unique=False,
        )

    op.create_table(
        "carts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "merchant_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("shop_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("shop_name"),
    )
    op.create_table(
        "moderation_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "request_type",
            sa.Enum("DELETE_REVIEW", name="moderationrequesttype"),
            nullable=False,
        ),
        sa.Column(
            "target_type",
            sa.Enum("REVIEW", name="moderationtargettype"),
            nullable=False,
        ),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "APPROVED", "REJECTED", name="moderationstatus"
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requester_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "total_amount", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PAID",
                "PARTIALLY_SHIPPED",
                "SHIPPED",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_groups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_order_groups_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "SUSPENDED", name="productstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_products_merchant_id"),
            ["merchant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_products_title"), ["title"], unique=False
        )

    op.create_table(
        "user_interests",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "category_id"),
    )
    with op.batch_alter_table("user_interests", schema=None) as batch_op:
        batch_op.create_index(
            "idx_user_interest_category_id", ["category_id"], unique=False
        )

    op.create_table(
        "cart_items",
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantity > 0", name="check_quantity_positive"),
        sa.ForeignKeyConstraint(["cart_id"], ["carts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("cart_id", "product_id"),
    )
    op.create_table(
        "merchant_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_group_id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PAID",
                "CANCELLED_BY_USER",
                "CANCELLED_BY_MERCHANT",
                "CANCELLED_BY_ADMIN",
                "SHIPPED",
                "DELIVERED",
                "COMPLETED",
                name="merchantorderstatus",
            ),
            nullable=False,
        ),
        sa.Column("cancel_deadline", sa.DateTime(), nullable=False),
        sa.Column(
            "subtotal_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("deleted_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["order_group_id"], ["order_groups.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("merchant_orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_merchant_orders_merchant_id"),
            ["merchant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_merchant_orders_order_group_id"),
            ["order_group_id"],
            unique=False,
        )

    op.create_table(
        "product_categories",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("product_id", "category_id"),
    )
    with op.batch_alter_table("product_categories", schema=None) as batch_op:
        batch_op.create_index(
            "idx_product_category_id", ["category_id"], unique=False
        )

    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("deleted_reason", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5", name="check_rating_range"
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "product_id", name="uq_user_product_review"
        ),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reviews_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reviews_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "wishlist_items",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "product_id"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "unit_price", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "item_status",
            sa.Enum(
                "NORMAL",
                "REFUNDING",
                "RETURNING",
                "EXCHANGING",
                "REFUNDED",
                "RETURNED",
                "EXCHANGED",
                name="itemstatus",
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0", name="check_order_quantity_positive"
        ),
        sa.ForeignKeyConstraint(
            ["merchant_order_id"], ["merchant_orders.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_order_items_merchant_order_id"),
            ["merchant_order_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_order_items_product_id"),
            ["product_id"],
            unique=False,
        )

    op.create_table(
        "order_shipping_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_order_id", sa.Integer(), nullable=False),
        sa.Column("recipient_name", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("full_address_text", sa.Text(), nullable=False),
        sa.Column("lat", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("lng", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("baidu_place_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_order_id"], ["merchant_orders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_order_id"),
    )
    op.create_table(
        "payment_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_order_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "INIT", "SUCCESS", "FAILED", "REFUNDED", name="paymentstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            sa.Enum("MOCK", "ALIPAY", "WECHAT", "CARD", name="paymentmethod"),
            nullable=False,
        ),
        sa.Column("provider_trade_no", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_order_id"], ["merchant_orders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payment_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payment_transactions_merchant_order_id"),
            ["merchant_order_id"],
            unique=False,
        )

    op.create_table(
        "shipments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_order_id", sa.Integer(), nullable=False),
        sa.Column("carrier_name", sa.String(length=50), nullable=True),
        sa.Column("tracking_no", sa.String(length=100), nullable=True),
        sa.Column(
            "shipping_status",
            sa.Enum(
                "NOT_SHIPPED", "IN_TRANSIT", "DELIVERED", name="shippingstatus"
            ),
            nullable=False,
        ),
        sa.Column("shipped_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_order_id"], ["merchant_orders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_order_id"),
    )
    op.create_table(
        "after_sale_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_order_id", sa.Integer(), nullable=False),
        sa.Column("order_item_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("RETURN", "EXCHANGE", "REFUND_ONLY", name="aftersaletype"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "REQUESTED",
                "MERCHANT_APPROVED",
                "MERCHANT_REJECTED",
                "ADMIN_APPROVED",
                "ADMIN_REJECTED",
                "IN_PROGRESS",
                "CLOSED",
                name="aftersalestatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_order_id"], ["merchant_orders.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"], ["order_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("after_sale_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_after_sale_requests_merchant_order_id"),
            ["merchant_order_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_after_sale_requests_order_item_id"),
            ["order_item_id"],
            unique=False,
        )

    op.create_table(
        "shipment_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shipment_id", sa.Integer(), nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("location_text", sa.String(length=200), nullable=True),
        sa.Column("status_text", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["shipment_id"], ["shipments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shipment_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shipment_events_shipment_id"),
            ["shipment_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shipment_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shipment_events_shipment_id"))

    op.drop_table("shipment_events")
    with op.batch_alter_table("after_sale_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_after_sale_requests_order_item_id"))
        batch_op.drop_index(
            batch_op.f("ix_after_sale_requests_merchant_order_id")
        )

    op.drop_table("after_sale_requests")
    op.drop_table("shipments")
    with op.batch_alter_table("payment_transactions", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_payment_transactions_merchant_order_id")
        )

    op.drop_table("payment_transactions")
    op.drop_table("order_shipping_snapshots")
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_items_product_id"))
        batch_op.drop_index(batch_op.f("ix_order_items_merchant_order_id"))

    op.drop_table("order_items")
    op.drop_table("wishlist_items")
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_user_id"))
        batch_op.drop_index(batch_op.f("ix_reviews_product_id"))

    op.drop_table("reviews")
    with op.batch_alter_table("product_categories", schema=None) as batch_op:
        batch_op.drop_index("idx_product_category_id")

    op.drop_table("product_categories")
    with op.batch_alter_table("merchant_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchant_orders_order_group_id"))
        batch_op.drop_index(batch_op.f("ix_merchant_orders_merchant_id"))

    op.drop_table("merchant_orders")
    op.drop_table("cart_items")
    with op.batch_alter_table("user_interests", schema=None) as batch_op:
        batch_op.drop_index("idx_user_interest_category_id")

    op.drop_table("user_interests")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_title"))
        batch_op.drop_index(batch_op.f("ix_products_merchant_id"))

    op.drop_table("products")
    with op.batch_alter_table("order_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_groups_user_id"))

    op.drop_table("order_groups")
    op.drop_table("moderation_requests")
    op.drop_table("merchant_profiles")
    op.drop_table("carts")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("addresses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_addresses_user_id"))

    op.drop_table("addresses")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_slug"))

    op.drop_table("categories")
    # ### end Alembic commands ###
