from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88065e0aa5c1"
down_revision = "2c78dcd73667"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_cancel_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_order_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("merchant_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING','APPROVED','REJECTED')",
            name="ck_order_cancel_request_status",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_order_id"], ["merchant_orders.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "order_cancel_requests", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_order_cancel_requests_merchant_id"),
            ["merchant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_order_cancel_requests_merchant_order_id"),
            ["merchant_order_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_order_cancel_requests_user_id"),
            ["user_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "order_cancel_requests", schema=None
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_cancel_requests_user_id"))
        batch_op.drop_index(
            batch_op.f("ix_order_cancel_requests_merchant_order_id")
        )
        batch_op.drop_index(batch_op.f("ix_order_cancel_requests_merchant_id"))

    op.drop_table("order_cancel_requests")
    # ### end Alembic commands ###
